---
- name: Real world play
  hosts: all

  roles:
    - role: tox
      vars:
        tox_extra_args: -- --hypervisor kvm --force --keep --filter "Kubernetes CAPI"

    - role: tox
      vars:
        tox_extra_args: -- --hide --hypervisor kvm --force --keep --delete --yes-i-really-know-what-i-do
