---
name: Build container image

"on":
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - openstack_image_manager/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - openstack_image_manager/**

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: osism/openstack-image-manager
          BUILD_OPTS: --file Containerfile
      - run: |
          scripts/push.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          REPOSITORY: osism/openstack-image-manager
        if: |
          github.repository == 'osism/openstack-image-manager' &&
          github.ref == 'refs/heads/main'
